
version: 2

models:
  - name: customer_dimension
    description: "A dimension table containing customer information."
    columns:
      - name: customer_id
        description: "The unique identifier for the customer."
      - name: customer_name
        description: "The name of the customer."
      - name: customer_address
        description: "The address of the customer."
      - name: customer_nationkey
        description: "The city where the customer lives."
      - name: customer_phone
        description: "The customer phone number"
      - name: customer_balance
        description: "The balance fund."
        
  - name: orders_fact
    description: "A fact table containing order information."
    columns:
      - name: order_id
        description: "The unique identifier for the order."
      - name: customer_id
        description: "The identifier of the customer who placed the order."
      - name: order_date
        description: "The date the order was placed."
      - name: order_total
        description: "The total amount of the order."
      - name: order_status
        description: "The order status for the order."
      - name: order_priority
        description: "The order priority is being shipped to."
