snowflake_project:
  # Config indicated by + and applies to all files under models/example/
  target: dev
  outputs:
    dev:
      type: snowflake
      account: nxbevjd-mx93582
      user: Anilaki
      password: Anil.143
      role: ACCOUNTADMIN
      database: DBT_LOAD
      warehouse: COMPUTE_WH
      schema: PUBLIC
